# Generated by Django 5.1.2 on 2025-01-26 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_clubbuttonlink_sectionimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionimage',
            name='css_identifier',
            field=models.CharField(default=1, help_text='CSS identifier for the section.', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
