# Generated by Django 5.1.2 on 2025-01-26 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_sectionimage_css_identifier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubbuttonlink',
            options={'verbose_name': 'Actualizarea linkului de la butonul verde', 'verbose_name_plural': 'Actualizarea linkului de la butonul verde'},
        ),
        migrations.AlterModelOptions(
            name='county',
            options={'verbose_name': 'Judet', 'verbose_name_plural': 'Județele'},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Actualizarea linkului de la butonul verde', 'verbose_name_plural': 'Actualizarea linkului de la butonul verde'},
        ),
        migrations.AlterModelOptions(
            name='lake',
            options={'verbose_name': 'Lacuri sau Balti', 'verbose_name_plural': 'Lacuri sau Balti'},
        ),
        migrations.AlterModelOptions(
            name='sectionimage',
            options={'verbose_name': 'Sectiunea de modificarea a pozelor', 'verbose_name_plural': 'Sectiunea de modificarea a pozelor'},
        ),
        migrations.AlterField(
            model_name='clubbuttonlink',
            name='button_link',
            field=models.URLField(help_text='Introdu URL unde vrei sa redirectioneze butonul verde'),
        ),
        migrations.AlterField(
            model_name='clubbuttonlink',
            name='button_text',
            field=models.CharField(default='Alăturați-vă clubului', help_text='Textul care vrei sa fie afisat pe butonul verde', max_length=100),
        ),
        migrations.AlterField(
            model_name='sectionimage',
            name='css_identifier',
            field=models.CharField(choices=[('hero-section', 'Imaginea intra in pagina'), ('welcome-section', 'Imagine sectiunea de bine ati venit'), ('fishing-explore-section', 'Imagine sectiunea de explorare'), ('testimonial-section', 'Imagine sectiunea de testimonial'), ('promo-section', 'Sectiunea de promotii')], help_text='Identificatorul CSS pentru secțiune. In ce sectiune din prima pagina vrei sa schimbi poza.', max_length=100, verbose_name='Sectiunea la care vrei sa ii schimbi imaginea:'),
        ),
        migrations.AlterField(
            model_name='sectionimage',
            name='image',
            field=models.ImageField(help_text='Imaginea noua pe care o incarci.', upload_to='section_images/', verbose_name='Imagine'),
        ),
        migrations.AlterField(
            model_name='sectionimage',
            name='section_name',
            field=models.CharField(help_text='Nume pentru urmarirea modificari', max_length=100, verbose_name='Numele modificari'),
        ),
    ]
