# Generated by Django 5.1.2 on 2025-01-26 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_tutorialvideo_remove_product_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorialvideo',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='tutorialvideo',
            name='video_url',
        ),
        migrations.AddField(
            model_name='tutorialvideo',
            name='iframe_code',
            field=models.TextField(default=1, help_text='Lipeste codul iframe aici'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tutorialvideo',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tutorialvideo',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
