# Generated by Django 5.1.2 on 2025-01-26 19:41

import django.db.models.deletion
from django.db import migrations, models
from django.utils.timezone import now


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_tutorialvideo_thumbnail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Categorie Tutorial',
                'verbose_name_plural': 'Categorii Tutoriale',
            },
        ),
        migrations.AlterModelOptions(
            name='tutorialvideo',
            options={'verbose_name': 'Video Tutorial', 'verbose_name_plural': 'Videouri Tutoriale'},
        ),
        migrations.RemoveField(
            model_name='tutorialvideo',
            name='description',
        ),
        migrations.AddField(
            model_name='tutorialvideo',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutorialvideo',
            name='youtuber_account',
            field=models.CharField(blank=True, help_text='Numele canalului YouTube al creatorului.', max_length=255),
        ),
        migrations.AlterField(
            model_name='tutorialvideo',
            name='iframe_code',
            field=models.TextField(help_text='Codul iframe pentru video-ul YouTube.'),
        ),
        migrations.AddField(
            model_name='tutorialvideo',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='main.tutorialcategory'),
        ),
    ]
