# Generated by Django 5.1.2 on 2025-01-26 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='referral_link',
            new_name='product_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
